jobs/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.conf.urls import patterns, url
from .models import Job
from .views import (JobCreate, JobList, JobDelete, JobUpdate, JobsFeed,
                    JobInactivate)


urlpatterns = patterns(
    '',
    url(r'^$', JobList.as_view(), name='jobs_list_all'),
    url(r'^rss$', JobsFeed(), name='jobs_feed'),
    url(r'^add/$', login_required(JobCreate.as_view()), name='jobs_add'),
    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Job), name='jobs_view'),
    url(r'^(?P<pk>\d+)/delete/$', login_required(JobDelete.as_view()), name='jobs_delete'),
    url(r'^(?P<pk>\d+)/update/$', login_required(JobUpdate.as_view()), name='jobs_update'),
    url(r'^(?P<pk>\d+)/inactivate/$', login_required(JobInactivate.as_view()),
        name='jobs_inactivate'),
)

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""


from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from waliki.settings import WALIKI_SLUG_PATTERN

from .views import buscador, irc, old_url_redirect


admin.autodiscover()

urlpatterns = patterns(
    '',
    # Static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    # Media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^irc/$', irc, name='irc'),
    url(r'^buscador/$', buscador, name='buscador'),

    url(r'^tutoring/', include('tutoring.urls')),

    url(r'^$', 'community.views.homepage', name='homepage'),
    url(r'^aprendiendo-python/', 'community.views.learning', name='aprendiendo'),
    url(r'^nosotros/', 'community.views.about_pyar', name='about_pyar'),
    url(r'^miembros/', 'community.views.members', name='pyar_members'),
    url(r'^lista/', 'community.views.mailing_list', name='mailing_list'),

    url(r'^noticias/', include('news.urls')),
    url(r'^empresas/', include('pycompanies.urls', namespace='companies')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^trabajo/', include('jobs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^eventos/', include('events.urls', namespace='events')),
    url(r'^planeta/', include('planet.urls')),
    url(r'^wiki/', include('waliki.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^email_confirmation/', include('email_confirm_la.urls',
                                         namespace='email_confirm_la')),
    url(r'^(pyar/)?(?P<slug>' + WALIKI_SLUG_PATTERN + ')/?',
        old_url_redirect, name='old_url_redirect'),
)

tutoring/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import patterns, url
from tutoring import views

urlpatterns = patterns(
    '',
    # url(r'^$', views.ListProject.as_view(), name='project_list_all'),
    url(r'^$', views.IndexView.as_view(), name='tutoring_index'),
    url(r'^mentor/$', views.ListMentor.as_view(), name='mentor_list_all'),
    url(r'^mentor/add/$', login_required(views.AddMentor.as_view()), name='new_mentor'),
    url(r'^mentor/update/(?P<slug>[-\w]+)/$', login_required(views.UpdateMentor.as_view()),
        name='update_mentor'),
    url(r'^mentor/(?P<slug>[-\w]+)/$', views.DisplayMentor.as_view(), name='display_mentor'),
    url(r'^apprentice/$', views.ListApprentice.as_view(), name='apprentice_list_all'),
    url(r'^apprentice/add/$',
        login_required(views.AddApprentice.as_view()), name='new_apprentice'),
    url(r'^apprentice/update/(?P<slug>[-\w]+)/$', login_required(views.UpdateApprentice.as_view()),
        name='update_apprentice'),
    url(r'^apprentice/(?P<slug>[-\w]+)/$', views.DisplayApprentice.as_view(),
        name='display_apprentice'),
    url(r'^project/$', views.ListProject.as_view(), name='project_list_all'),
    url(r'^project/add/$', login_required(views.AddProject.as_view()), name='new_project'),
    url(r'^project/update/(?P<pk>[0-9]+)/$', login_required(views.UpdateProject.as_view()),
        name='update_project'),
    url(r'^project/(?P<pk>[0-9]+)/$', views.DisplayProject.as_view(), name='display_project'),
    url(r'^mentorship/$', views.ListMentorship.as_view(), name='mentorship_list_all'),
    url(r'^mentorship/add/$', login_required(views.AddMentorship.as_view()),
        name='new_mentorship'),
    url(r'^mentorship/update/(?P<pk>[0-9]+)/$', login_required(views.UpdateMentorship.as_view()),
        name='update_mentorship'),
    url(r'^mentorship/(?P<pk>[0-9]+)/$', views.DisplayMentorship.as_view(),
        name='display_mentorship'),
)

tutoring/models.py
from django.core.urlresolvers import reverse
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext as _
from django.db import models
from taggit.managers import TaggableManager


class Mentor(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL)
    description = models.TextField(blank=True, null=True)
    available = models.BooleanField(default=True, verbose_name=_('Disponible'))
    start_date = models.DateTimeField(auto_now_add=True)
    slots = models.PositiveIntegerField(default=2, validators=[MaxValueValidator(4),
                                                               MinValueValidator(1)])
    tags = TaggableManager(verbose_name=_('Skills'))

    def __str__(self):
        return self.owner.username

    def get_absolute_url(self):
        return reverse('display_mentor', kwargs={'slug': self.owner.username})


class Apprentice(models.Model):
    STATUS_TRAINING = 'T'
    STATUS_IDLE = 'I'
    STATUS_WAITING = 'W'

    STATUS_CHOICES = (
        (STATUS_TRAINING, _('Entretenando')),
        (STATUS_IDLE, _('Inactivo')),
        (STATUS_WAITING, _('Buscando mentor')),
    )
    owner = models.OneToOneField(settings.AUTH_USER_MODEL)
    description = models.TextField(blank=True, null=True, verbose_name=_('Descripción'))
    start_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_WAITING,
                              verbose_name=_('Estado'))

    tags = TaggableManager(verbose_name=_('Intereses'))

    def __str__(self):
        return self.owner.username

    def get_absolute_url(self):
        return reverse('display_apprentice', kwargs={'slug': self.owner.username})


class Project(models.Model):
    LOOKING_FOR_MENTOR = 'M'
    LOOKING_FOR_APPRENTICE = 'A'
    STATUS_OPEN = 'O'
    STATUS_IN_COURSE = 'I'
    STATUS_CLOSED = 'C'

    LOOKING_CHOICES = (
        (LOOKING_FOR_MENTOR, _('Buscando mentor')),
        (LOOKING_FOR_APPRENTICE, _('Buscando aprendiz')),
    )
    STATUS_CHOICES = (
        (STATUS_OPEN, _('Abierto')),
        (STATUS_IN_COURSE, _('En curso')),
        (STATUS_CLOSED, _('Cerrado')),
    )
    title = models.CharField(max_length=250, verbose_name=_('Título'))
    description = models.TextField(blank=True, verbose_name=_('Descripción'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_OPEN)
    link_repo = models.URLField(blank=True, verbose_name=_('URL del repositorio'))
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    looking_for = models.CharField(max_length=1, choices=LOOKING_CHOICES,
                                   default=LOOKING_FOR_MENTOR)
    multiple_mentors = models.BooleanField(default=True, verbose_name=_('Múltiples mentores'))
    multiple_apprentices = models.BooleanField(
        default=True, verbose_name=_('Múltiples aprendices'))
    tags = TaggableManager()
    mentors = models.ManyToManyField(Mentor, blank=True)
    apprentices = models.ManyToManyField(Apprentice, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('display_project', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-id']


class Mentorship(models.Model):
    STATUS_ON_HOLD = 'O'
    STATUS_IN_COURSE = 'I'
    STATUS_CLOSED = 'C'

    STATUS_CHOICES = (
        (STATUS_IN_COURSE, _('En curso')),
        (STATUS_ON_HOLD, _('En espera')),
        (STATUS_CLOSED, _('Cerrado')),
    )
    project = models.ForeignKey(Project, null=True, blank=True, verbose_name=_('Proyecto'))
    owner = models.ForeignKey(Mentor, verbose_name=_('Mentor'))
    apprentice = models.ForeignKey(Apprentice, verbose_name=_('Aprendiz'))
    start_date = models.DateField(auto_now_add=True, verbose_name=_('Fecha de inicio'))
    end_date = models.DateField(null=True, blank=True, verbose_name=_('Fecha de finalización'))
    blog_link = models.URLField(null=True, blank=True, verbose_name=_('URL del blog'))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_IN_COURSE,
                              verbose_name=_('Estado'))

    def __str__(self):
        return '{} - {} - {}'.format(self.owner, self.apprentice, self.start_date)

    def get_absolute_url(self):
        return reverse('display_mentorship', kwargs={'pk': self.pk})

tutoring/forms.py
from django import forms
from .models import Mentor, Apprentice, Project, Mentorship
from django.utils.translation import ugettext_lazy as _
from crispy_forms.layout import Submit, Reset
from crispy_forms.helper import FormHelper
from django.core.exceptions import ValidationError


class MentorForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(MentorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('mentor_submit', _('Guardar')))
        self.helper.add_input(Reset('mentor_reset', _('Limpiar'),
                                    css_class='btn-default'))

    class Meta:
        model = Mentor
        exclude = ('owner',)


class ApprenticeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ApprenticeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('apprentice_submit', _('Guardar')))
        self.helper.add_input(Reset('apprentice_reset', _('Limpiar'),
                                    css_class='btn-default'))

    class Meta:
        model = Apprentice
        exclude = ('owner',)


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('project_submit', _('Guardar')))
        self.helper.add_input(Reset('project_reset', _('Limpiar'),
                                    css_class='btn-default'))

    class Meta:
        model = Project
        exclude = ('owner',)


class MentorshipForm(forms.ModelForm):

    def __init__(self, mentor=None, *args, **kwargs):
        super(MentorshipForm, self).__init__(*args, **kwargs)
        if mentor is not None:
            self.instance.owner = mentor
        self.helper = FormHelper()
        self.helper.add_input(Submit('mentorship_submit', _('Guardar')))
        self.helper.add_input(Reset('mentorship_reset', _('Limpiar'),
                                    css_class='btn-default'))

    def clean(self):
        active = Mentorship.STATUS_IN_COURSE
        status = self.cleaned_data.get('status')
        if status == active:
            mentor = self.instance.owner
            max_slots = mentor.slots
            mentorships = mentor.mentorship_set.filter(status=active)
            if self.instance.pk:
                mentorships = mentorships.exclude(id=self.instance.pk)
            mentorships = mentorships.count()
            if mentorships >= max_slots:
                raise ValidationError(u'No te quedan slots disponibles.')

    class Meta:
        model = Mentorship
        exclude = ('owner', 'project',)

tutoring/views.py
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.http import Http404
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from community.views import OwnedObject, FilterableList
from .models import Project, Mentor, Apprentice, Mentorship
from .forms import MentorForm, ApprenticeForm, ProjectForm, MentorshipForm
from django.views.generic.detail import SingleObjectMixin


class AddMentor(CreateView):
    model = Mentor
    form_class = MentorForm

    def dispatch(self, request, *args, **kwargs):
        try:
            mentor = Mentor.objects.get(owner=request.user)
            return redirect(reverse('update_mentor', kwargs={'slug': mentor.owner}))
        except Mentor.DoesNotExist:
            return super(AddMentor, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AddMentor, self).form_valid(form)


class DisplayMentor(DetailView):
    model = Mentor
    form_class = MentorForm
    slug_field = 'owner__username'

    def get_context_data(self, **kwargs):
        context = super(DisplayMentor, self).get_context_data(**kwargs)
        return context


class UpdateMentor(UpdateView, OwnedObject):
    model = Mentor
    form_class = MentorForm
    slug_field = 'owner__username'


# class DeleteMentor(DeleteView, OwnedObject):
#     model = Mentor
#     slug_field = 'owner__username'
#     success_url = reverse_lazy('new_mentor')


class ListMentor(ListView, FilterableList):
    model = Mentor
    paginate_by = 20


class AddApprentice(CreateView):
    model = Apprentice
    form_class = ApprenticeForm

    def dispatch(self, request, *args, **kwargs):
        try:
            apprentice = Apprentice.objects.get(owner=request.user)
            return redirect(reverse('update_apprentice', kwargs={'slug': apprentice.owner}))
        except Apprentice.DoesNotExist:
            return super(AddApprentice, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AddApprentice, self).form_valid(form)


class DisplayApprentice(DetailView):
    model = Apprentice
    form_class = ApprenticeForm
    slug_field = 'owner__username'

    def get_context_data(self, **kwargs):
        context = super(DisplayApprentice, self).get_context_data(**kwargs)
        return context


class UpdateApprentice(UpdateView, OwnedObject):
    model = Apprentice
    form_class = ApprenticeForm
    slug_field = 'owner__username'


# class DeleteApprentice(DeleteView, OwnedObject):
#     model = Apprentice
#     slug_field = 'owner__username'
#     success_url = reverse_lazy('new_apprentice')


class ListApprentice(ListView, FilterableList):
    model = Apprentice
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(ListApprentice, self).get_context_data(**kwargs)
        context['status_choices'] = Apprentice.STATUS_CHOICES
        return context


class AddProject(CreateView):
    model = Project
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AddProject, self).form_valid(form)


class DisplayProject(DetailView):
    model = Project
    form_class = ProjectForm

    def get_context_data(self, **kwargs):
        context = super(DisplayProject, self).get_context_data(**kwargs)
        return context


class ListProject(ListView, FilterableList):
    model = Project
    paginate_by = 20


class UpdateProject(UpdateView, OwnedObject):
    model = Project
    form_class = ProjectForm
#
#
# class DeleteProject(DeleteView, OwnedObject):
#     model = Project
#     success_url = reverse_lazy('new_project')


class AddMentorship(CreateView):
    model = Mentorship
    form_class = MentorshipForm

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            return super(AddMentorship, self).dispatch(request, *args, **kwargs)
        else:
            return redirect(reverse('new_mentor'))

    def get_form_kwargs(self):
        kwargs = super(AddMentorship, self).get_form_kwargs()
        kwargs['mentor'] = self.request.user.mentor
        return kwargs

    def form_valid(self, form):
        form.instance.owner = Mentor.objects.get(owner=self.request.user)
        return super(AddMentorship, self).form_valid(form)


class UpdateMentorship(UpdateView, SingleObjectMixin):
    model = Mentorship
    form_class = MentorshipForm

    def get_object(self, *args, **kwargs):
        obj = super(UpdateMentorship, self).get_object(*args, **kwargs)
        try:
            if not obj.owner.owner == self.request.user:
                raise Http404()
        except AttributeError:
            pass
        return obj


class DisplayMentorship(DetailView):
    model = Mentorship
    form_class = MentorshipForm

    def get_context_data(self, **kwargs):
        context = super(DisplayMentorship, self).get_context_data(**kwargs)
        return context


class ListMentorship(ListView):
    model = Mentorship
    paginate_by = 20


class IndexView(TemplateView):
    template_name = 'tutoring/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['mentors'] = Mentor.objects.filter(available=True)
        context['apprentices'] = Apprentice.objects.filter(status=Apprentice.STATUS_WAITING)
        context['projects'] = Project.objects.all()[:5]
        return context

templates/tutoring/_tutoring_tags.html
{% load i18n %}
{% if tags_type == 'apprentice' %}
    {% trans 'Intereses' %}:
    {% for tag in object.tags.all %}
          <a class="label label-default" href="{% url 'apprentice_list_all' %}?tag_{{ tag.slug }}=1" >{{ tag.name }}</a>
    {% endfor %}
{% elif tags_type == 'mentor' %}
    {% trans 'Habilidades' %}:
    {% for tag in object.tags.all %}
          <a class="label label-default" href="{% url 'mentor_list_all' %}?tag_{{ tag.slug }}=1" >{{ tag.name }}</a>
    {% endfor %}
{% else %}
    {% trans 'Etiquetas' %}:
    {% for tag in object.tags.all %}
          <a class="label label-default" href="{% url 'project_list_all' %}?tag_{{ tag.slug }}=1" >{{ tag.name }}</a>
    {% endfor %}
{% endif %}

templates/tutoring/apprentice_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% trans 'Eliminar aprendiz' %}</h2>
	    </div>
	    <form action="" method="post">{% csrf_token %}
            <p>{% trans 'Está seguro que desea eliminar al aprendiz' %} "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
	</div>
</main>
{% endblock %}

templates/tutoring/apprentice_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>
                {% trans 'Detalles del aprendiz' %} {{ object.owner }}
            </h2>
	    </div>
        <p>{% trans 'Descripción:' %} {{ object.description }}</p>
        <p>{% trans 'Desde:' %} {{ object.start_date }}</p>
        <p>{% trans 'Estado:' %} {{ object.get_status_display }}</p>
        <p>{% include "tutoring/_tutoring_tags.html" with tags_type="apprentice" %}
{#            {% for tag in object.tags.all %}#}
{#                 {{ tag.name }},#}
{#            {% endfor %}#}
        </p>

	</div>
</main>
{% endblock %}

templates/tutoring/apprentice_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% if form.instance.id %}
	    			{% trans 'Actualizando información' %}
	    		{% else %}
	    			{% trans 'Agregar un nuevo aprendiz' %}
	    		{% endif %}
	    	</h2>
	    </div>
	    {{ form.media }}
	    {% crispy form %}
	</div>
</main>
{% endblock %}

templates/tutoring/apprentice_list.html
{% extends "base_site.html" %}
{% load devtags %}
{% load i18n staticfiles pagination_tags %}
{% block title %}Aprendices{% endblock %}
{% block left-column %}

<!-- Project list -->
<section>
    <div class="col-md-12">
        <div class="page-header">
            <h2>{% trans 'Aprendices' %}
                <span class="section-button-group pull-right">
                    <a href="{% url 'new_apprentice' %}" class="btn btn-info">
                        {% if user.apprentice %}
                            {% trans 'Actualizar mis datos' %}
                        {% else %}
                            {% trans 'Quiero aprender' %}
                        {% endif %}
                    </a>
                </span>
            </h2>
        </div>

        {% if object_list %}
            {% regroup object_list|dictsort:"status" by status as object2_list %}
            {% for obj in object2_list %}
                {% for i in status_choices %}
                    {% if obj.grouper == i.0 %}
                        <h3>{{ i.1 }}</h3>
                    {% endif %}
                {% endfor %}
                {% for object in obj.list %}
                    <h4>
                        <a href="{{ object.get_absolute_url }}">{{ object.owner }}</a>
                    </h4>
                    <p>{{ object.description|html2text|truncatewords:50 }}</p>
                    <div class="text-muted">
                        {% include "tutoring/_tutoring_tags.html" with tags_type="apprentice" %}
                    </div>
                {% endfor %}
            {% endfor %}

            {% paginate %}
        {% else %}
            <div class="col-md-12">
                <p>{% trans 'La búsqueda no produjo resultados.' %}</p>
            </div>
        {% endif %}



            <!-- <div class="pull-right">
                <a href="{% url 'jobs_feed' %}" class="badge">
                    <i class="fa fa-rss"></i> RSS
                </a>
           </div> -->
    </div>
</section>
{% endblock %}

{% block right-column %}
<section class="list-group">
    <header class="list-group-item">
        <h3 class="list-group-item-heading">{% trans 'Tutorías' %}</h3>
    </header>
    <article class="list-group-item">
        <div class="section-button-group">
            <a href="{% url 'apprentice_list_all' %}" class="btn btn-info btn-block">{% trans 'Ver apredices' %}</a>
            <a href="{% url 'mentor_list_all' %}" class="btn btn-info btn-block">{% trans 'Ver mentores' %}</a>
            <a href="{% url 'mentorship_list_all' %}" class="btn btn-info btn-block">{% trans 'Ver mentorías' %}</a>
            <a href="{% url 'project_list_all' %}" class="btn btn-info btn-block">{% trans 'Ver proyectos' %}</a>
        </div>
    </article>
</section>
{{ block.super }}
{% include "_tags_filtering_form.html" %}
{% endblock %}

templates/tutoring/mentor_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% trans 'Eliminar mentor' %}</h2>
	    </div>
	    <form action="" method="post">{% csrf_token %}
            <p>{% trans 'Está seguro que desea eliminar al mentor' %} "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
	</div>
</main>
{% endblock %}

templates/tutoring/mentorship_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% trans 'Detalles de la tutoría' %} {{ object }} </h2>
            {% if object.owner.owner == request.user %}
                <span class="section-button-group pull-right" style="position: absolute;right: 14px;top: 32px;">
                    <a href="{% url 'update_mentorship' object.pk %}" class="btn btn-info">{% trans 'Editar' %}</a>
                </span>
            {% endif %}
	    </div>
{#        <p>{% trans 'Proyecto:' %} {{ object.project }}</p>#}
        <p>{% trans 'Mentor:' %} {{ object.owner }}</p>
        <p>{% trans 'Aprendiz:' %} {{ object.apprentice.owner }}</p>
        <p>{% trans 'Fecha de inicio:' %} {{ object.start_date }}</p>
        <p>{% trans 'Fecha de finalización:' %} {{ object.end_date }}</p>
        <p>{% trans 'Estado:' %} {{ object.get_status_display }}</p>
        <p>{% trans 'Enlace al blog:' %} <a href="{{ object.blog_link }}" target="_blank">
            {{ object.blog_link }}</a></p>
	</div>
</main>
{% endblock %}

templates/tutoring/mentorship_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% if form.instance.id %}
	    			{% trans 'Actualizando información' %}
	    		{% else %}
	    			{% trans 'Agregar nueva tutoría' %}
	    		{% endif %}
	    	</h2>
	    </div>
	    {{ form.media }}
	    {% crispy form %}
	</div>
</main>
{% endblock %}

templates/tutoring/project_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>
                {% trans 'Detalles del proyecto' %} {{ object.title }}
            </h2>
            {% if object.owner == request.user %}
                <span class="section-button-group pull-right" style="position: absolute;right: 14px;top: 32px;">
                    <a href="{% url 'update_project' object.pk %}" class="btn btn-info">{% trans 'Editar' %}</a>
                </span>
            {% endif %}
	    </div>
        <p>{% trans 'Descripción:' %} {{ object.description }}</p>
        <p>{% trans 'Estado:' %} {{ object.get_status_display }}</p>
        <p>{% trans 'Enlace al repositorio: ' %}<a href="{{ object.link_repo }}" target="_blank">
            {{ object.link_repo }}</a></p>
        <p>{% trans 'Buscando:' %} {{ object.get_looking_for_display }}</p>
        <p>{% trans 'Múltiples mentores:' %}
            {% if object.multiple_mentors %}
	    		{% trans 'Se aceptan múltiples mentores' %}
	    	{% else %}
	    		{% trans 'No se aceptan múltiples mentores' %}
            {% endif %}
        </p>
        <p>{% trans 'Múltiples aprendices:' %}
            {% if object.multiple_apprentices %}
	    		{% trans 'Se aceptan múltiples aprendices' %}
	    	{% else %}
	    		{% trans 'No se aceptan múltiples aprendices' %}
            {% endif %}
        </p>
        <p>{% trans 'Mentores:' %} {% for mentor in object.mentors.all %}
                 {{ mentor.owner }},
            {% endfor %}
        </p>
        <p>{% trans 'Aprendices:' %} {% for apprentice in object.apprentices.all %}
                 {{ apprentice.owner }},
            {% endfor %}
        </p>
        <p>{% trans 'Tags:' %} {% for tag in object.tags.all %}
                 {{ tag.name }},
            {% endfor %}
        </p>

	</div>
</main>
{% endblock %}